#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env.local"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  .env.local already exists. Delete it first to regenerate."
  exit 1
fi

SESSION_SECRET=$(openssl rand -hex 32)
CSRF_SECRET=$(openssl rand -hex 32)

cat > "$ENV_FILE" << EOF
# Generated by scripts/generate-env.sh — DO NOT COMMIT
SESSION_SECRET=${SESSION_SECRET}
CSRF_SECRET=${CSRF_SECRET}
EOF

echo "✅ Generated $ENV_FILE with random secrets"
echo "   SESSION_SECRET: ${SESSION_SECRET:0:8}..."
echo "   CSRF_SECRET: ${CSRF_SECRET:0:8}..."
