#!/usr/bin/env bash
# hermes-setup.sh — Install and configure Hermes Agent for AFK integration
# Usage: hermes-setup.sh [--verify] [--force]
#
# Installs Hermes Agent, creates .hermes/ config directory, and verifies
# the installation can communicate with Claude Code.
set -euo pipefail

HERMES_VERSION="${HERMES_VERSION:-0.14.0}"
HERMES_CONFIG_DIR=".hermes"
HERMES_SKILLS_DIR="${HERMES_CONFIG_DIR}/skills"
FORCE=false
VERIFY_ONLY=false

for arg in "$@"; do
    case "$arg" in
        --force) FORCE=true ;;
        --verify) VERIFY_ONLY=true ;;
        --help|-h)
            echo "Usage: hermes-setup.sh [--verify] [--force]"
            echo ""
            echo "Options:"
            echo "  --verify   Check installation status without installing"
            echo "  --force    Reinstall even if already installed"
            echo ""
            echo "Environment:"
            echo "  HERMES_VERSION   Version to install (default: ${HERMES_VERSION})"
            exit 0
            ;;
    esac
done

check_hermes() {
    if command -v hermes >/dev/null 2>&1; then
        INSTALLED_VERSION=$(hermes --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo "unknown")
        echo "✅ Hermes installed: v${INSTALLED_VERSION}"
        return 0
    else
        echo "❌ Hermes not found in PATH"
        return 1
    fi
}

check_claude() {
    if command -v claude >/dev/null 2>&1; then
        echo "✅ Claude Code CLI available"
        return 0
    else
        echo "⚠️  Claude Code CLI not found — Hermes can install but cannot delegate"
        return 1
    fi
}

check_config() {
    local pass=0
    [ -d "$HERMES_CONFIG_DIR" ] && echo "✅ ${HERMES_CONFIG_DIR}/ exists" || { echo "❌ ${HERMES_CONFIG_DIR}/ missing"; pass=1; }
    [ -f "${HERMES_CONFIG_DIR}/config.yaml" ] && echo "✅ config.yaml exists" || { echo "❌ config.yaml missing"; pass=1; }
    [ -d "$HERMES_SKILLS_DIR" ] && echo "✅ skills/ directory exists" || { echo "❌ skills/ missing"; pass=1; }
    return $pass
}

if [ "$VERIFY_ONLY" = true ]; then
    echo "=== Hermes Installation Verification ==="
    FAIL=0
    check_hermes || FAIL=1
    check_claude || true
    check_config || FAIL=1

    if [ "$FAIL" -eq 0 ]; then
        echo ""
        echo "✅ Hermes setup verified"
        exit 0
    else
        echo ""
        echo "❌ Hermes setup incomplete — run: scripts/hermes-setup.sh"
        exit 1
    fi
fi

echo "=== Hermes Agent Setup v${HERMES_VERSION} ==="

# Step 1: Check prerequisites
echo ""
echo "--- Prerequisites ---"
check_claude || true

if ! command -v npm >/dev/null 2>&1 && ! command -v pip >/dev/null 2>&1; then
    echo "❌ Neither npm nor pip found. Install Node.js or Python first."
    exit 1
fi

# Step 2: Install Hermes
if check_hermes && [ "$FORCE" = false ]; then
    echo "Hermes already installed. Use --force to reinstall."
else
    echo ""
    echo "--- Installing Hermes Agent v${HERMES_VERSION} ---"
    if command -v npm >/dev/null 2>&1; then
        npm install -g "hermes-agent@${HERMES_VERSION}" 2>&1 || {
            echo "⚠️  npm install failed, trying pip..."
            pip install "hermes-agent==${HERMES_VERSION}" 2>&1 || {
                echo "❌ Installation failed via both npm and pip."
                echo "Install manually: https://github.com/hermes-agent/hermes-agent"
                exit 1
            }
        }
    else
        pip install "hermes-agent==${HERMES_VERSION}" 2>&1 || {
            echo "❌ pip install failed."
            echo "Install manually: https://github.com/hermes-agent/hermes-agent"
            exit 1
        }
    fi
    echo "✅ Hermes Agent installed"
fi

# Step 3: Create directory structure
echo ""
echo "--- Creating config directories ---"
mkdir -p "$HERMES_CONFIG_DIR"
mkdir -p "$HERMES_SKILLS_DIR"
echo "✅ Created ${HERMES_CONFIG_DIR}/ and ${HERMES_SKILLS_DIR}/"

# Step 4: Create config template if it doesn't exist
if [ ! -f "${HERMES_CONFIG_DIR}/config.yaml" ] || [ "$FORCE" = true ]; then
    echo "--- Creating config template ---"
    cat > "${HERMES_CONFIG_DIR}/config.yaml" << 'YAML'
# Hermes Agent Configuration for DeepSecure AFK Workflow
# Generated by scripts/hermes-setup.sh
# Docs: docs/design/afk-workflow-enablement.md (Feature 8)

agent:
  name: "deepsecure-hermes"
  version: "0.14.0"

memory:
  backend: "sqlite"
  path: ".hermes/memory.db"
  search: "fts5"

delegation:
  primary: "claude-code"
  models:
    - name: "claude"
      command: "claude --print"
      flags: "--permission-mode auto --max-budget-usd 5"

notifications:
  channels:
    - type: "slack"
      webhook_env: "DEEPSECURE_SLACK_WEBHOOK"
    - type: "telegram"
      token_env: "DEEPSECURE_TELEGRAM_TOKEN"
      chat_id_env: "DEEPSECURE_TELEGRAM_CHAT_ID"
    - type: "macos"
      enabled: true

skills:
  directory: ".hermes/skills/"
  auto_create: true
YAML
    echo "✅ Created ${HERMES_CONFIG_DIR}/config.yaml"
else
    echo "config.yaml already exists (use --force to overwrite)"
fi

# Step 5: Create .gitignore for Hermes runtime files
if [ ! -f "${HERMES_CONFIG_DIR}/.gitignore" ]; then
    cat > "${HERMES_CONFIG_DIR}/.gitignore" << 'GITIGNORE'
# Hermes runtime files (not committed)
memory.db
memory.db-wal
memory.db-shm
*.log
*.pid
GITIGNORE
    echo "✅ Created ${HERMES_CONFIG_DIR}/.gitignore"
fi

# Step 6: Final verification
echo ""
echo "--- Final Verification ---"
FAIL=0
check_hermes || FAIL=1
check_config || FAIL=1

echo ""
if [ "$FAIL" -eq 0 ]; then
    echo "✅ Hermes setup complete"
    echo ""
    echo "Next steps:"
    echo "  1. Set notification env vars (optional):"
    echo "     export DEEPSECURE_SLACK_WEBHOOK=https://hooks.slack.com/..."
    echo "     export DEEPSECURE_TELEGRAM_TOKEN=..."
    echo "  2. Start observer: scripts/hermes-observer.sh start"
    echo "  3. Test: scripts/hermes-setup.sh --verify"
else
    echo "⚠️  Setup completed with warnings — check errors above"
    exit 1
fi
