"""Unit tests for the UserSession model."""

import uuid
from datetime import datetime, timedelta, timezone

from app.models.user_session import (
    DEFAULT_SESSION_DURATION_HOURS,
    UserSession,
    generate_session_id,
    get_default_expiry,
)


class TestGenerateSessionId:
    """Tests for the session ID generation function."""

    def test_generates_string(self):
        """Session ID should be a string."""
        session_id = generate_session_id()
        assert isinstance(session_id, str)

    def test_has_correct_prefix(self):
        """Session ID should start with 'usess-' prefix."""
        session_id = generate_session_id()
        assert session_id.startswith("usess-")

    def test_contains_uuid(self):
        """Session ID should contain a valid UUID after the prefix."""
        session_id = generate_session_id()
        uuid_part = session_id.replace("usess-", "")
        # Should not raise ValueError if valid UUID
        uuid.UUID(uuid_part)

    def test_generates_unique_ids(self):
        """Each call should generate a unique session ID."""
        ids = [generate_session_id() for _ in range(100)]
        assert len(set(ids)) == 100


class TestGetDefaultExpiry:
    """Tests for the default expiry calculation."""

    def test_returns_datetime(self):
        """Default expiry should return a datetime."""
        expiry = get_default_expiry()
        assert isinstance(expiry, datetime)

    def test_is_timezone_aware(self):
        """Default expiry should be timezone-aware (UTC)."""
        expiry = get_default_expiry()
        assert expiry.tzinfo is not None
        assert expiry.tzinfo == timezone.utc

    def test_is_8_hours_in_future(self):
        """Default expiry should be approximately 8 hours from now."""
        before = datetime.now(timezone.utc)
        expiry = get_default_expiry()
        after = datetime.now(timezone.utc)

        expected_min = before + timedelta(hours=DEFAULT_SESSION_DURATION_HOURS)
        expected_max = after + timedelta(hours=DEFAULT_SESSION_DURATION_HOURS)

        assert expected_min <= expiry <= expected_max


class TestUserSessionModel:
    """Tests for the UserSession SQLAlchemy model."""

    def test_instantiation_with_required_fields(self):
        """UserSession can be instantiated with only required fields."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.user_id == "sarah@acme.com"
        assert session.idp_issuer == "https://acme.okta.com"

    def test_default_session_id_generated(self):
        """Session ID should be generated by default."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        # Default is only applied when accessing the attribute
        # For now, just verify the model accepts the field
        assert session.session_id is None or session.session_id.startswith("usess-")

    def test_custom_session_id(self):
        """Custom session ID can be provided."""
        custom_id = "usess-custom-123"
        session = UserSession(
            session_id=custom_id,
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.session_id == custom_id

    def test_organization_id_optional(self):
        """Organization ID should be optional (None by default)."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.organization_id is None

    def test_organization_id_can_be_set(self):
        """Organization ID can be set."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            organization_id="org-acme-123",
        )

        assert session.organization_id == "org-acme-123"

    def test_revoked_at_optional(self):
        """Revoked at should be optional (None by default)."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.revoked_at is None

    def test_idp_metadata_optional(self):
        """IdP metadata should be optional (None by default)."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.idp_metadata is None

    def test_custom_expiry(self):
        """Custom expiry can be provided."""
        custom_expiry = datetime.now(timezone.utc) + timedelta(hours=4)
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=custom_expiry,
        )

        assert session.expires_at == custom_expiry

    def test_repr(self):
        """String representation should include key fields."""
        session = UserSession(
            session_id="usess-test-123",
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime(2026, 1, 21, 18, 0, 0, tzinfo=timezone.utc),
        )

        repr_str = repr(session)
        assert "usess-test-123" in repr_str
        assert "sarah@acme.com" in repr_str


class TestUserSessionProperties:
    """Tests for UserSession computed properties."""

    def test_is_expired_false_for_future_expiry(self):
        """is_expired should return False when expires_at is in the future."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime.now(timezone.utc) + timedelta(hours=1),
        )

        assert session.is_expired is False

    def test_is_expired_true_for_past_expiry(self):
        """is_expired should return True when expires_at is in the past."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime.now(timezone.utc) - timedelta(hours=1),
        )

        assert session.is_expired is True

    def test_is_revoked_false_by_default(self):
        """is_revoked should return False when revoked_at is None."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
        )

        assert session.is_revoked is False

    def test_is_revoked_true_when_revoked(self):
        """is_revoked should return True when revoked_at is set."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            revoked_at=datetime.now(timezone.utc),
        )

        assert session.is_revoked is True

    def test_is_active_true_when_not_expired_and_not_revoked(self):
        """is_active should return True when session is valid."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime.now(timezone.utc) + timedelta(hours=1),
        )

        assert session.is_active is True

    def test_is_active_false_when_expired(self):
        """is_active should return False when session is expired."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime.now(timezone.utc) - timedelta(hours=1),
        )

        assert session.is_active is False

    def test_is_active_false_when_revoked(self):
        """is_active should return False when session is revoked."""
        session = UserSession(
            user_id="sarah@acme.com",
            idp_issuer="https://acme.okta.com",
            expires_at=datetime.now(timezone.utc) + timedelta(hours=1),
            revoked_at=datetime.now(timezone.utc),
        )

        assert session.is_active is False


class TestUserSessionTablename:
    """Tests for table configuration."""

    def test_tablename(self):
        """Table name should be 'user_sessions'."""
        assert UserSession.__tablename__ == "user_sessions"
